---
title: "STAT463 Final project"
output: pdf_document
date: "2024-11-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(astsa)
```





```{r}

yearTemp <- read.csv("Yearly.csv")

YearlyTemp <- yearTemp %>%
  filter(Year <= 2023, Source == "gcag")

 
temp_TS <- YearlyTemp[, c("Year", "Mean")]
temp_TS <- temp_TS[order(temp_TS$Year), ]
temp_TS <- ts(temp_TS$Mean, 
                   start = min(temp_TS$Year), 
                   end = max(temp_TS$Year), 
                   frequency = 1)



co2Data <- read.csv("https://ourworldindata.org/grapher/annual-co2-emissions-per-country.csv?v=1&csvType=filtered&useColumnShortNames=false&country=~OWID_WRL")
co2Data <- co2Data[co2Data$Year >= 1850, ]
c02_TS <- co2Data[, c("Year", "Annual.CO..emissions")]
c02_TS <- c02_TS[order(c02_TS$Year), ]
c02_TS <- ts(c02_TS$Annual.CO..emissions, 
                   start = min(c02_TS$Year), 
                   end = max(c02_TS$Year), 
                   frequency = 1)



plot(c02_TS)

plot(log(c02_TS))


plot(diff(log(c02_TS)))

acf2(diff(log(c02_TS)))


```

```{r}

Temp_model <- lm(Year~value, data = co2Data)
summary(Temp_model)
plot(resid(Temp_model), type = "l")

acf(diff(log(abs(resid(Temp_model)))))
pacf(diff(log(abs(resid(Temp_model)))))


```



```{r}







```















